In [4]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [8]:
model = Sequential()
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 3)                 27        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.get_weights()[0].shape

(5, 3)

In [13]:
model.get_weights()[0]

array([[-0.7565629 ,  0.796323  , -0.1864723 ],
       [ 0.6666058 ,  0.22642487,  0.35553902],
       [ 0.37484866, -0.863654  , -0.7292357 ],
       [-0.5223988 , -0.49925366,  0.35697788],
       [-0.74715495, -0.21860373,  0.7882865 ]], dtype=float32)

In [14]:
model.get_weights()[1].shape

(3, 3)

In [15]:
model.get_weights()[1]

array([[ 0.5617554 ,  0.8249152 , -0.06281689],
       [ 0.69405085, -0.42858994,  0.5784498 ],
       [ 0.45024925, -0.36854535, -0.8132957 ]], dtype=float32)

In [16]:
model.get_weights()[2].shape

(3,)

In [17]:
model.get_weights()[2]

array([0., 0., 0.], dtype=float32)

In [18]:
model.get_weights()[3].shape

(3, 1)

In [19]:
model.get_weights()[3]

array([[-0.32223552],
       [-1.1034952 ],
       [ 0.9113792 ]], dtype=float32)

In [20]:
model.get_weights()[4].shape

(1,)

In [21]:
model.get_weights()[4]

array([0.], dtype=float32)

In [22]:
#sentiment-analysis-simplernn

In [39]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [40]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [41]:
tokenizer.fit_on_texts(docs)

In [42]:
len(tokenizer.word_index)

18

In [43]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [45]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [46]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [47]:
tokenizer.document_count

10

In [44]:
from keras.utils import pad_sequences
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
sequences = pad_sequences(sequences,padding='post')
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]])

In [48]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [49]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 5, 2)              34        
                                                                 
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [50]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [51]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [52]:
len(X_train[2])

141

In [53]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [54]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32])

In [55]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [56]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 9s 10ms/step - loss: 0.6944 - accuracy: 0.5034 - val_loss: 0.6939 - val_accuracy: 0.5014
Epoch 2/5
782/782 [==============================] - 8s 11ms/step - loss: 0.6932 - accuracy: 0.5038 - val_loss: 0.6946 - val_accuracy: 0.4996
Epoch 3/5
782/782 [==============================] - 8s 11ms/step - loss: 0.6930 - accuracy: 0.5034 - val_loss: 0.6947 - val_accuracy: 0.4990
Epoch 4/5
782/782 [==============================] - 8s 10ms/step - loss: 0.6928 - accuracy: 0.5058 - val_loss: 0.6942 - val_accuracy: 0.5072
Epoch 5/5
782/782 [==============================] - 8s 10ms/step - loss: 0.6929 - accuracy: 0.4995 - val_loss: 0.6951 - val_accuracy: 0.5016
